# Generated by Django 5.2.6 on 2026-06-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='required_formula',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
